### ISSUE TITLE
Make the algorithm more efficient

### ISSUE THREAD

**Issue by CCruzG** [GenArtRepo/differential-growth#1]
The growth function iterates over all the points in the rope, and it is called within run, which also iterates through all the points twice (once for separation and once for cohesion). These two functions can be merged into one, with one loop –instead of three– where points are updated (node.run()), and then new nodes are inserted if required.

https://github.com/GenArtRepo/differential-growth/blob/9297842987435c0dd174f9e44813134b31a6e8c1/rope.js#L20-L53

**Comment by crarojasca** [comment]
Hi @CCruzG, the algorithm was optimized with various modifications in the PR are all the details.
